version: "2"
run:
  go: '1.24.2'
  modules-download-mode: readonly
  allow-parallel-runners: true
  timeout: 3m
linters:
  default: standard
formatters:
  enable:
    - gofmt
    - goimports
issues:
  uniq-by-line: false
output:
  show-stats: true