name: Go Linter

on:
  workflow_call:

jobs:
  linter:
    runs-on: ubuntu-24.04
    steps:
      - name: Github Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          cache: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1481404843c368bc19ca9406f87d6e0fc97bdcfd
        with:
          version: v2.0
          args: --verbose --timeout=3m