name: PR Labeller

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  labeller:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b
        with:
          configuration-path: .github/labeller.yml
          sync-labels: true