name: PR Labeller

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  labeller:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    runs-on: ubuntu-24.04
    steps:
      - name: Label
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9
        with:
          configuration-path: .github/labeller.yml
          sync-labels: true